FROM eclipse-temurin:21-jdk as builder

WORKDIR /app

COPY m2/repository /root/.m2/repository
COPY mvnw mvnw
COPY .mvn .mvn
COPY pom.xml pom.xml
COPY src src

RUN ./mvnw clean package -DskipTests -Dmaven.repo.local=/root/.m2/repository

ENTRYPOINT ["sh", "-c", "./mvnw spring-boot:run"]
